# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17.0.8
      uses: actions/setup-java@v1
      with:
        java-version: 17.0.8
        distribution: 'temurin'
    - name: Setup Java JDK
      uses: actions/setup-java@v3.13.0
      with:
          java-version: '11'
          distribution: 'temurin'
    - name: Unity - Test runner
      uses: game-ci/unity-test-runner@v3.1.0
    - name: Docker build and push
      uses: cloudposse/github-action-docker-build-push@1.13.1

    - name: Build with Gradle
      run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon
    - name: Run Unit and Integration Test
      run: ./gradlew test --console verbose
